version: '3.7'

services:
  db:
    image: postgres:15
    container_name: basketlog_db
    volumes:
      - postgresdata:/var/lib/postgresql/basketlog_data
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
  auth-service:
    image: auth-service
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    env_file:
      - .env-non-dev
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  postgresdata: