"""unique names for teams and photo_urls

Revision ID: 1a19e5f990d7
Revises: e4e902237bd1
Create Date: 2025-03-31 15:26:12.844984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a19e5f990d7'
down_revision: Union[str, None] = 'e4e902237bd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coaches', ['photo_url'])
    op.create_unique_constraint(None, 'players', ['photo_url'])
    op.create_unique_constraint(None, 'teams', ['name'])
    op.create_unique_constraint(None, 'teams', ['logo_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_constraint(None, 'coaches', type_='unique')
    # ### end Alembic commands ###
