"""Added birth_date to Coach model

Revision ID: 6a47a067b6dc
Revises: cf21e40e0b2e
Create Date: 2025-04-13 07:38:44.559630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a47a067b6dc'
down_revision: Union[str, None] = 'cf21e40e0b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaches', sa.Column('birth_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaches', 'birth_date')
    # ### end Alembic commands ###
