"""changed naming expireD_at -> expires_at in refresh_tokens

Revision ID: fb35813726aa
Revises: d05a565e2de5
Create Date: 2025-01-23 18:23:55.761155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb35813726aa'
down_revision: Union[str, None] = 'd05a565e2de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expires_at', sa.DateTime(), nullable=False))
    op.drop_column('refresh_tokens', 'expired_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('expired_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('refresh_tokens', 'expires_at')
    # ### end Alembic commands ###
